title: 7ynk3r
description: A personal blog about technology and thoughts
author: Juan Rodriguez
email: hello@7ynk3r.github.io
url: "https://7ynk3r.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
